title: Radek Molenda (@qrczeno) | Blog
description: "Qrczeno personal blog including: Ruby, Elixir and my deepest thoughts"
url: "http://radekmolenda.github.io/"
author:
  name: "Radek Molenda"
  email: "radek.molenda@gmail.com"
  url: "http://radekmolenda.github.io/"

# Build settings
baseurl: /
markdown: rdiscount
rdiscount:
  extensions: [smart]
source: .
destination: ./_site
permalink: /:year/:month/:day/:title.html
paginate: 8
paginate_path: /page:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
gems: [jekyll-paginate]
